# Generated by Django 4.2.11 on 2026-05-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Agentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Colas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Respuestas_Automaticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('bug', 'Bug/Error'), ('feature', 'Nueva Funcionalidad'), ('support', 'Soporte General'), ('consulta', 'Consulta'), ('incidente', 'Incidente')], default='support', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo (Sin revisar)'), ('triaje', 'En Triaje'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('pendiente', 'Pendiente de Información'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20)),
                ('estado_triage', models.CharField(choices=[('nuevo', 'Nuevo (Sin revisar)'), ('triaje', 'En Triaje'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('pendiente', 'Pendiente de Información'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('agente_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tikects_app.agentes')),
                ('cerrado_por_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to='tikects_app.agentes')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tikects_app.cliente')),
                ('cola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tikects_app.tickets_colas')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tikects_app.tickets_servicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReasignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reasignacion', models.DateTimeField(auto_now_add=True)),
                ('agente_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_anterior', to='tikects_app.agentes')),
                ('agente_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_nuevo', to='tikects_app.agentes')),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes')),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tikects_app.direcciones'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tikects_app.grupos_clientes'),
        ),
        migrations.CreateModel(
            name='AsignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes')),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Agentes_Por_Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.grupos_agentes')),
            ],
        ),
        migrations.CreateModel(
            name='AgenteGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reasignacion', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('agente_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='tikects_app.agentes')),
                ('agente_reasignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_reasignacion', to='tikects_app.agentes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes_genericos', to='tikects_app.tickets_servicios')),
            ],
        ),
    ]
