# Generated by Django 6.0.5 on 2026-05-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direcciones',
            new_name='Gerencias',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='gerencia',
        ),
    ]
