# Generated by Django 6.0.5 on 2026-05-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0002_rename_direcciones_gerencias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerencias',
            new_name='Gerencia',
        ),
    ]
