# Generated by Django 6.0.5 on 2026-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0005_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentes',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agentes',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
