# Generated by Django 6.0.5 on 2026-09-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0006_agentes_apellido_agentes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='cola',
        ),
        migrations.DeleteModel(
            name='Tickets_Colas',
        ),
    ]
