# Generated by Django 6.0.5 on 2026-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0007_remove_tickets_cola_delete_tickets_colas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='descripcion_solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
