# Generated by Django 6.0.5 on 2026-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0008_tickets_descripcion_solucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApariencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_texto', models.CharField(default='© 2026 Tickpro. Todos los derechos reservados.', max_length=255)),
                ('email_soporte', models.EmailField(default='soporte@tickpro.com', max_length=254)),
                ('telefono_soporte', models.CharField(default='(0212) 123-4567', max_length=50)),
            ],
        ),
    ]
