# Generated by Django 6.0.5 on 2026-10-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0009_configuracionapariencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionapariencia',
            name='footer_texto',
        ),
    ]
