# Generated by Django 6.0.5 on 2026-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0010_remove_configuracionapariencia_footer_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionapariencia',
            name='icono_sistema',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
